# Site settings
title: The résumé of Josha Ho
author:
  address:
      town: Saskatoon, SK
      postcode: S7K 3B1
      country: Canada
  email: josha@joshaho.com
  name: Josha Ho
  title: Master's Student at University of Saskatchewan
  # twitter_username: hojosha
  github_username:  joshaho
  phone: 1(360) 312-7202
  repository: https://github.com/nternetinspired/jekyll-resume
  website: http://www.joshaho.com
description: > # this means to ignore newlines until "baseurl:"
  Powered by Jekyll, and Github Pages ready, Jekyll-cv is a lightweight and lightning-fast
  html résumé making machine from @nternetinspired. Because web developers shouldn't
  showcase their skills on bits of dead tree.
baseurl: "/resume/" # the subpath of your site, e.g. /blog/
url: "http://joshaho.github.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
